happy_smile = []
happy_smile.append(":")
happy_smile.append(")")
happy_smile.append(":)")
happy_smile.append("-_-")
happy_smile.append("_ :)_")
happy_smile.append("_-)")
print(happy_smile)
print(len(happy_smile), "len")
print("_pop_")
happy_smile.pop()
print(happy_smile)

happy_smile.pop(0)
print(happy_smile)

print()
removed = happy_smile.pop(0)
print(removed, "removed element")
print(happy_smile)
