my_nums = [4, 4, 5, 6, 5, 5, 8, 4, 7]
print(my_nums)
print(type(my_nums))
print(dir(my_nums))
print(my_nums.count(5))
my_nums.append(25)
print(my_nums)
my_nums.insert(2, -5)
print(my_nums, "insert")
print()
my_nums.extend('saq')
print(my_nums)
other_nums = my_nums.copy()
my_nums.clear()
print()
other_nums.pop(-1)
print(my_nums, other_nums)
print(id(my_nums), id(other_nums))
print(len(my_nums), len(other_nums))
